In [1]:
from modify_label import *

In [2]:
## Generate input: 3D numpy array of size [H,W,D];
## Possible values of the array elements are 0,1,2;
inputs = np.zeros([3,3,2])
inputs[:,0,0], inputs[:,1,0] = 1., 2.
inputs[0,:,1], inputs[2,:,1] = 1., 2.

## Generate the expected output: binary 3D numpy array of size (H,W,D);
expected_output =  np.zeros([3,3,2])
expected_output[:,0,0], expected_output[:,1,0] = 1., 1.
expected_output[0,:,1], expected_output[2,:,1] = 1., 1.

## Pass the input array to the function:
## array elements with the value 2. are re-assigned a new value, 1.;
outputs = modify_label(inputs)

## Check whether the function output matches the expected output (arrays equality);
np.testing.assert_array_equal(outputs, expected_output)

In [3]:
## Output the input and function output arrays;
print(inputs[:,:,0], '\n')
print(inputs[:,:,1], '\n')
print(outputs[:,:,0], '\n')
print(outputs[:,:,1], '\n')

[[1. 2. 0.]
 [1. 2. 0.]
 [1. 2. 0.]] 

[[1. 1. 1.]
 [0. 0. 0.]
 [2. 2. 2.]] 

[[1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]] 

[[1. 1. 1.]
 [0. 0. 0.]
 [1. 1. 1.]] 

